apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: threadforge-system
spec:
  serviceName: clickhouse
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
      annotations:
        sidecar.istio.io/userVolume: '{"istio-custom-root-cert":{"configMap":{"name":"istio-ca-root-cert"}}}'
        sidecar.istio.io/userVolumeMount: '{"istio-custom-root-cert":{"mountPath":"/etc/certs","readOnly":true}}'
    spec:
      serviceAccountName: clickhouse
      containers:
        - name: clickhouse
{{- if .Values.image.digest }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
{{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLICKHOUSE_HTTP_PORT
              value: "8123"
            - name: CLICKHOUSE_TCP_PORT
              value: "9000"
            - name: CLICKHOUSE_INTERSERVER_HTTP_PORT
              value: "9009"
          ports:
            - containerPort: 9000
            - containerPort: 8123
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: clickhouse-data
