apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres
  namespace: observability
  labels:
    threadforge.io/component: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  namespaceSelector:
    matchNames:
      - postgres
  podMetricsEndpoints:
    - port: metrics
      interval: 10s
      {{- include "prometheus.metricNameAsciiOnly" . | nindent 6 }}
