apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: redis
  namespace: observability
  labels:
    threadforge.io/component: redis
spec:
  selector:
    matchLabels:
      app: redis
  namespaceSelector:
    matchNames:
      - redis
  podMetricsEndpoints:
    - port: metrics
      interval: 10s
      {{- include "prometheus.metricNameAsciiOnly" . | nindent 6 }}
