apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smp-router
  namespace: observability
  labels:
    threadforge.io/component: smp-router
spec:
  selector:
    matchLabels:
      app: smp-router
  namespaceSelector:
    matchNames:
      - threadforge
  endpoints:
    - port: http
      interval: 10s
      path: /metrics
