# ==============================================================================
# ThreadForge — Actuator Plane
# ------------------------------------------------------------------------------
# Final execution surface for approved plans.
#
# HARD GUARANTEES:
#   - Governance gate is authoritative
#   - Execution is impossible when disabled
#   - All denials are observable and auditable
# ==============================================================================

from __future__ import annotations

import shutil
import subprocess  # nosec B404: Safe usage - all commands are internally generated by governance
from typing import Any

from runtime.actuator.governance_gate import ActuatorGovernanceGate
from runtime.actuator.plan_state_registry import PlanState, PlanStateRegistry
from runtime.actuator.plan_validator import PlanValidator
from runtime.actuator.spire_verifier import SpireVerifier
from runtime.signal.fabric import emit


class ActuatorPlane:
    """Executes approved, validated plans — ONLY if governance allows."""

    def __init__(self):
        self.validator = PlanValidator()
        self.registry = PlanStateRegistry()

    # ------------------------------------------------------------------
    # MAIN ENTRYPOINT
    # ------------------------------------------------------------------
    def execute(self, plan: dict[str, Any]) -> dict[str, Any]:
        """Attempt to execute a plan.

        This function is constitutionally constrained.
        """
        plan_id = plan.get("plan_id", "unknown")

        # --------------------------------------------------------------
        # 1. GOVERNANCE GATE (ABSOLUTE AUTHORITY)
        # --------------------------------------------------------------
        if not ActuatorGovernanceGate.execution_allowed():
            denial = {
                "plan_id": plan_id,
                "status": "DENIED",
                "reason": "Actuator execution disabled by governance",
                "governance": ActuatorGovernanceGate.snapshot(),
            }

            # Record + emit
            self.registry.set_state(plan_id, PlanState.REJECTED, denial)
            emit("ACTUATOR_DENIED", denial)

            return denial

        # --------------------------------------------------------------
        # 2. VALIDATION (STRUCTURAL + APPROVAL)
        # --------------------------------------------------------------
        self.validator.validate(plan)

        # --------------------------------------------------------------
        # 3. SPIRE IDENTITY VERIFICATION (NON-NEGOTIABLE)
        # --------------------------------------------------------------
        SpireVerifier().verify(plan)

        # --------------------------------------------------------------
        # 4. EXECUTION (SAFE PATH ONLY)
        # --------------------------------------------------------------
        results: list[dict[str, Any]] = []

        for cmd in plan.get("commands", []):
            try:
                # B603: Safe - cmd is from validated plan (generated by governance, never external input)
                # List form prevents shell injection
                if not isinstance(cmd, (list, tuple)) or not cmd:
                    results.append({"command": cmd, "status": "ERROR", "error": "invalid command format"})
                    continue
                if shutil.which(str(cmd[0])) is None:
                    results.append({"command": cmd, "status": "ERROR", "error": f"executable {cmd[0]} not found"})
                    continue
                subprocess.call(
                    cmd, shell=False
                )  # nosec B603: cmd validated by governance and list form prevents shell injection
                results.append({"command": cmd, "status": "OK"})
            except Exception as exc:
                results.append({"command": cmd, "status": f"ERROR: {exc}"})

        execution_result = {
            "plan_id": plan_id,
            "status": "EXECUTED",
            "results": results,
        }

        self.registry.set_state(plan_id, PlanState.EXECUTED, execution_result)
        emit("ACTUATOR_EXECUTED", execution_result)

        return execution_result
