apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "identity-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "identity-controller.name" . }}
    chart: {{ include "identity-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}