apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: spiffe-identity-logs
  namespace: istio-system
spec:
  accessLogging:
  - providers:
    - name: envoy
    filter:
      expression: "true"
    disabled: false
