# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workload.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "workload.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eworkload.proto\x12\x12spiffe.workload.v1"\x16\n\x14\x46\x65tchX509SVIDRequest"0\n\x08X509SVID\x12\x11\n\tspiffe_id\x18\x01 \x01(\t\x12\x11\n\tx509_svid\x18\x02 \x01(\x0c"O\n\x10X509SVIDResponse\x12+\n\x05svids\x18\x01 \x03(\x0b\x32\x1c.spiffe.workload.v1.X509SVID\x12\x0e\n\x06\x62undle\x18\x02 \x01(\x0c\x32v\n\x11SpiffeWorkloadAPI\x12\x61\n\rFetchX509SVID\x12(.spiffe.workload.v1.FetchX509SVIDRequest\x1a$.spiffe.workload.v1.X509SVIDResponse"\x00\x62\x06proto3'  # noqa: E501
)  # noqa: E501

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "workload_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FETCHX509SVIDREQUEST"]._serialized_start = 38
    _globals["_FETCHX509SVIDREQUEST"]._serialized_end = 60
    _globals["_X509SVID"]._serialized_start = 62
    _globals["_X509SVID"]._serialized_end = 110
    _globals["_X509SVIDRESPONSE"]._serialized_start = 112
    _globals["_X509SVIDRESPONSE"]._serialized_end = 191
    _globals["_SPIFFEWORKLOADAPI"]._serialized_start = 193
    _globals["_SPIFFEWORKLOADAPI"]._serialized_end = 311
# @@protoc_insertion_point(module_scope)
