# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import workload_pb2 as workload__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in workload_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SpiffeWorkloadAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchX509SVID = channel.unary_unary(
            "/spiffe.workload.v1.SpiffeWorkloadAPI/FetchX509SVID",
            request_serializer=workload__pb2.FetchX509SVIDRequest.SerializeToString,
            response_deserializer=workload__pb2.X509SVIDResponse.FromString,
            _registered_method=True,
        )


class SpiffeWorkloadAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchX509SVID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SpiffeWorkloadAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "FetchX509SVID": grpc.unary_unary_rpc_method_handler(
            servicer.FetchX509SVID,
            request_deserializer=workload__pb2.FetchX509SVIDRequest.FromString,
            response_serializer=workload__pb2.X509SVIDResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("spiffe.workload.v1.SpiffeWorkloadAPI", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("spiffe.workload.v1.SpiffeWorkloadAPI", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SpiffeWorkloadAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchX509SVID(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/spiffe.workload.v1.SpiffeWorkloadAPI/FetchX509SVID",
            workload__pb2.FetchX509SVIDRequest.SerializeToString,
            workload__pb2.X509SVIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
