apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:

    # Public HTTPS Gateway
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.istio.tls.secretName }}
      hosts:
        - "grafana.threadforge.local"

    # Internal Mesh Gateway
    - port:
        number: 15443
        name: https-internal
        protocol: TLS
      tls:
        mode: ISTIO_MUTUAL
      hosts:
        - "grafana.internal.threadforge.local"
