apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: observability
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: grafana
  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana
        threadforge-tier: observability
      annotations:
        {{ toYaml .Values.podAnnotations | nindent 8 }}
        sidecar.istio.io/userVolume: '{"istio-custom-root-cert":{"configMap":{"name":"istio-ca-root-cert"}}}'
        sidecar.istio.io/userVolumeMount: '{"istio-custom-root-cert":{"mountPath":"/etc/certs","readOnly":true}}'

    spec:
      serviceAccountName: {{ .Values.identity.serviceAccount }}
      priorityClassName: threadforge-medium
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}

      containers:
        - name: grafana
{{- if .Values.image.digest }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
{{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
{{- end }}
          ports:
            - containerPort: 3000

          # Minimal PodSecurity compliance for container
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          resources: {{ toYaml .Values.resources | nindent 12 }}

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "{{ .Values.admin.user }}"
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.admin.existingSecret }}
                  key: {{ .Values.admin.existingSecretPasswordKey }}
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: "tempoSearch"
{{- if .Values.env }}
{{ toYaml .Values.env | nindent 12 }}
{{- end }}


          volumeMounts:
            - name: storage
              mountPath: /var/lib/grafana
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards/threadforge
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: providers
              mountPath: /etc/grafana/provisioning/dashboards
            - name: istio-custom-root-cert
              mountPath: /etc/certs
              readOnly: true

      volumes:
        - name: dashboards
          configMap:
            name: grafana-dashboards

        - name: datasources
          configMap:
            name: grafana-datasources

        - name: providers
          configMap:
            name: grafana-dashboard-providers

        - name: istio-custom-root-cert
          configMap:
            name: istio-ca-root-cert

  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
