apiVersion: v1
kind: ConfigMap
metadata:
  name: threadforge-global-config
  namespace: {{ .Values.global.threadforge.namespace }}
  labels:
    app.kubernetes.io/name: threadforge
    threadforge/component: global
data:
  REGISTRY_URL: {{ .Values.global.threadforge.registry }}
  POSTGRES_HOST: {{ .Values.global.threadforge.postgres.host }}
  POSTGRES_USER: {{ .Values.global.threadforge.postgres.user }}
  REDIS_HOST: {{ .Values.global.threadforge.redis.host }}
