apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vectordb
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: vectordb
  namespaceSelector:
    matchNames:
      - vectordb
  endpoints:
    - port: metrics
      interval: 15s
