apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: civsim
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: civsim
  namespaceSelector:
    matchNames:
      - threadforge
  endpoints:
    - port: http
      interval: 15s
