apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: minio
  namespaceSelector:
    matchNames:
      - minio
  endpoints:
    - port: metrics
      interval: 20s
