apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tf-workers
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: tf-worker
  namespaceSelector:
    matchNames:
      - threadforge
  endpoints:
    - port: metrics
      interval: 10s
