apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tf-vector-router
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: vector-router
  namespaceSelector:
    matchNames:
      - threadforge
  endpoints:
    - port: http
      interval: 10s
