apiVersion: v1
kind: Pod
metadata:
  name: curl-inject
  namespace: observability
  labels:
    app: curl-inject
    sidecar.istio.io/inject: "true"
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  containers:
    - name: curl
      image: registry.threadforge.local:30500/mirror/docker.io/curlimages/curl@sha256:846c5f0324b40f833b9a1fa3d5a667ac0f2b4712c9a39cae8cafe890286c52f2
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
