[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name        tail
    Path        /var/log/kubernetes/audit/audit.log
    Parser      json
    Tag         k8s_audit
    DB          /var/log/flb_k8s_audit.db

[FILTER]
    Name   grep
    Match  k8s_audit
    Regex  $.objectRef.resource    ^(configmaps|deployments|statefulsets|networkpolicies)$

[FILTER]
    Name   grep
    Match  k8s_audit
    Regex  $.verb    ^(update|patch|apply|create|delete)$

[OUTPUT]
    Name   http
    Match  k8s_audit
    Host   clickhouse
    Port   8123
    URI    /?query=INSERT%20INTO%20default.k8s_audit_events%20FORMAT%20JSONEachRow
    Format json
    Header Content-Type: application/json
