apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  namespace: observability
  labels:
    release: tf-observability
    threadforge.io/component: istio-control-plane
spec:
  selector:
    matchLabels:
      app: istiod
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-monitoring
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
