apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tempo-allow-otel-collector
  namespace: tempo
spec:
  podSelector:
    matchLabels:
      app: tempo
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchLabels:
              app.kubernetes.io/component: opentelemetry-collector
      ports:
        - protocol: TCP
          port: 4317
  policyTypes:
    - Ingress
