apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: observability
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"registry.threadforge.local:30500":{}}}
