import shutil
import subprocess  # nosec B404: Safe usage - all commands are internally generated by reflex planner
from typing import Any

from runtime.identity.capability_resolver import derive_capabilities
from runtime.identity.context import IdentityContext
from runtime.identity.guards import require
from runtime.signal.fabric import emit


class ActuatorGate:
    """The ActuatorGate is the ONLY place where execution is allowed.

    If a command is not executed here, it is not executed at all.
    """

    # ------------------------------------------------------------------
    # GLOBAL EXECUTION LOCK
    # ------------------------------------------------------------------
    EXECUTION_ENABLED = False  # HARD DEFAULT: OFF

    # ------------------------------------------------------------------
    # MAIN ENTRYPOINT
    # ------------------------------------------------------------------
    def execute(
        self,
        plan: dict[str, Any],
        approval: dict[str, Any],
        environment: str,
        identity: IdentityContext,
    ) -> dict[str, Any]:
        """Execute an approved plan.

        Phase 8: Authority is derived from identity via capabilities.
        This function enforces ALL safety requirements.
        """
        # --------------------------------------------------------------
        # 1. Global execution lock
        # --------------------------------------------------------------
        if not self.EXECUTION_ENABLED:
            emit(
                "ACTUATION_BLOCKED",
                {
                    "reason": "Execution globally disabled",
                    "plan_id": plan.get("plan_id"),
                },
            )
            return self._denied("Execution globally disabled")

        # --------------------------------------------------------------
        # 1.5. Identity verification and capability derivation
        # --------------------------------------------------------------
        if not identity.attested:
            return self._denied("Identity not attested")

        # Phase 8: Derive capabilities from identity (fail closed)
        try:
            capabilities = derive_capabilities(identity)
        except RuntimeError as e:
            return self._denied(f"Capability derivation failed: {e}")

        # Phase 8: Require actuation approval capability (fail closed)
        try:
            require("actuation.approve", capabilities)
        except PermissionError as e:
            return self._denied(f"Actuation capability required: {e}")

        # --------------------------------------------------------------
        # 2. Approval verification
        # --------------------------------------------------------------
        if approval.get("decision") != "APPROVE":
            return self._denied("Approval decision is not APPROVE")

        if approval.get("plan_digest") != plan.get("digest"):
            return self._denied("Approval digest does not match plan")

        if environment not in approval.get("allowed_environments", []):
            return self._denied("Environment not authorized")

        # --------------------------------------------------------------
        # 3. Governance policy check
        # --------------------------------------------------------------
        if not plan.get("safe", False):
            return self._denied("Plan marked as unsafe")

        # --------------------------------------------------------------
        # 4. Execute commands
        # --------------------------------------------------------------
        execution_results = []

        for cmd in plan.get("commands", []):
            try:
                # B603: Safe - cmd is from validated plan (generated by reflex, never external input)
                # List form prevents shell injection
                if not isinstance(cmd, (list, tuple)) or not cmd:
                    execution_results.append({"command": cmd, "status": "ERROR", "error": "invalid command format"})
                    continue
                if shutil.which(str(cmd[0])) is None:
                    execution_results.append(
                        {"command": cmd, "status": "ERROR", "error": f"executable {cmd[0]} not found"}
                    )
                    continue
                subprocess.call(
                    cmd, shell=False
                )  # nosec B603: cmd validated by plan generation; list form prevents shell injection
                execution_results.append({"command": cmd, "status": "OK"})
            except Exception as exc:
                execution_results.append({"command": cmd, "status": f"ERROR: {exc}"})

        emit(
            "ACTUATION_EXECUTED",
            {
                "plan_id": plan.get("plan_id"),
                "results": execution_results,
            },
        )

        return {
            "status": "EXECUTED",
            "results": execution_results,
        }

    # ------------------------------------------------------------------
    # DENIAL HANDLER
    # ------------------------------------------------------------------
    def _denied(self, reason: str) -> dict[str, Any]:
        emit(
            "ACTUATION_DENIED",
            {"reason": reason},
        )
        return {
            "status": "DENIED",
            "reason": reason,
        }
