# ==============================================================================
# ThreadForge — Actuator Core
# ------------------------------------------------------------------------------
# The ONLY place where commands may actually execute.
#
# Preconditions:
#   - Plan validated
#   - Plan approved
#   - Governance explicitly allows actuation
#
# Default posture: SAFE / DISABLED
# ==============================================================================

from __future__ import annotations

import shutil
import subprocess  # nosec B404: Safe usage - all commands are internally generated by reflex planner
from typing import Any

from runtime.actuation.plan_validator import PlanValidationError, validate_plan
from runtime.signal.fabric import emit


class ActuationDisabledError(Exception):
    pass


class ActuatorCore:
    """Actuator Plane executor.

    This class must remain boring.
    No reasoning.
    No branching intelligence.
    """

    def __init__(self, *, allow_actuation: bool = False):
        # HARD GOVERNANCE SWITCH
        self.allow_actuation = allow_actuation

    # ------------------------------------------------------------------
    def execute_plan(self, plan: dict[str, Any]) -> dict[str, Any]:
        """Execute an approved, validated plan."""
        # --------------------------------------------------------------
        # 1. Validate plan (hard gate)
        # --------------------------------------------------------------
        try:
            validate_plan(plan)
        except PlanValidationError as exc:
            emit(
                "ACTUATION_BLOCKED",
                {
                    "reason": str(exc),
                    "plan_id": plan.get("metadata", {}).get("plan_id"),
                },
            )
            raise

        # --------------------------------------------------------------
        # 2. Governance switch
        # --------------------------------------------------------------
        if not self.allow_actuation:
            emit(
                "ACTUATION_BLOCKED",
                {
                    "reason": "Actuation disabled by governance",
                    "plan_id": plan.get("metadata", {}).get("plan_id"),
                },
            )
            raise ActuationDisabledError("Actuation disabled by governance")

        # --------------------------------------------------------------
        # 3. Execute commands
        # --------------------------------------------------------------
        results: list[dict[str, Any]] = []

        for cmd in plan["commands"]:
            try:
                # B603: Safe - cmd is from validated plan (generated by reflex, never external input)
                # List form prevents shell injection
                if not isinstance(cmd, (list, tuple)) or not cmd:
                    results.append({"command": cmd, "status": "ERROR", "error": "invalid command format"})
                    break
                if shutil.which(str(cmd[0])) is None:
                    results.append({"command": cmd, "status": "ERROR", "error": f"executable {cmd[0]} not found"})
                    break
                subprocess.run(cmd, check=True, shell=False)  # nosec B603: cmd validated by plan generation
                results.append({"command": cmd, "status": "OK"})
            except Exception as exc:
                results.append({"command": cmd, "status": "ERROR", "error": str(exc)})
                break

        emit(
            "ACTUATION_EXECUTED",
            {
                "plan_id": plan["metadata"]["plan_id"],
                "results": results,
            },
        )

        return {
            "status": "completed",
            "plan_id": plan["metadata"]["plan_id"],
            "results": results,
        }
