apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    istio-injection: enabled
    threadforge.io/mesh: allowed
    pod-security.kubernetes.io/enforce: restricted
    threadforge.identity: "true"
