apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: loki-mtls
  namespace: {{ .Release.Namespace }}
spec:
  host: loki.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
