apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-envoy-bootstrap
  namespace: observability
data:
  envoy.yaml: |
    node:
      id: "blackbox-sidecar"
      cluster: "blackbox"
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 9901
    static_resources:
      listeners:
        - name: listener_outbound
          address:
            socket_address:
              address: 127.0.0.1
              port_value: 8443
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    stat_prefix: outbound
                    cluster: minio_envoy_cluster
      clusters:
        - name: spire_agent
          type: STATIC
          connect_timeout: 5s
          http2_protocol_options: {}
          load_assignment:
            cluster_name: spire_agent
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        pipe:
                          path: /run/spire/sockets/socket
        - name: minio_envoy_cluster
          connect_timeout: 5s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: minio_envoy_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: minio-envoy.minio.svc.cluster.local
                          port_value: 8443
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                tls_certificate_sds_secret_configs:
                  - name: spiffe://identity.threadforge.local/ns/observability/sa/blackbox
                    sds_config:
                      api_config_source:
                        api_type: GRPC
                        grpc_services:
                          - envoy_grpc:
                              cluster_name: spire_agent
                validation_context_sds_secret_config:
                  name: spiffe://identity.threadforge.local
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      grpc_services:
                        - envoy_grpc:
                            cluster_name: spire_agent

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blackbox-sa
  namespace: observability

