apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: router-dr
  namespace: threadforge
spec:
  host: router
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
