apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: router-mesh-gateway
  namespace: threadforge
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 15443
        name: tls-mesh
        protocol: TLS
      tls:
        mode: ISTIO_MUTUAL
      hosts:
        - "router.threadforge.svc.cluster.local"
