apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: router-rate-limit
  namespace: threadforge
spec:
  workloadSelector:
    labels:
      app: router
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
      patch:
        operation: INSERT_AFTER
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            stat_prefix: router_ratelimit
            token_bucket:
              max_tokens: 20
              tokens_per_fill: 20
              fill_interval: 1s
            filter_enabled:
              runtime_key: local_rate_limit_enabled
              default_value:
                numerator: 100
                denominator: HUNDRED
            filter_enforced:
              runtime_key: local_rate_limit_enforced
              default_value:
                numerator: 100
                denominator: HUNDRED
