# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services.

NOTE: This file is a generated server skeleton. Service methods are unimplemented
and raise NotImplementedError by design. There is no runtime plugin registration
server implemented in the repository; the skeleton exists for protobuf contract
completeness only.
"""

import api_pb2 as api__pb2
import grpc

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in api_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RegistrationStub(object):
    """Registration is the service advertised by the Plugins."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
            "/pluginregistration.Registration/GetInfo",
            request_serializer=api__pb2.InfoRequest.SerializeToString,
            response_deserializer=api__pb2.PluginInfo.FromString,
            _registered_method=True,
        )
        self.NotifyRegistrationStatus = channel.unary_unary(
            "/pluginregistration.Registration/NotifyRegistrationStatus",
            request_serializer=api__pb2.RegistrationStatus.SerializeToString,
            response_deserializer=api__pb2.RegistrationStatusResponse.FromString,
            _registered_method=True,
        )


class RegistrationServicer(object):
    """Registration is the service advertised by the Plugins."""

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Generated server skeleton: method unimplemented by design")

    def NotifyRegistrationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Generated server skeleton: method unimplemented by design")


def add_RegistrationServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetInfo,
            request_deserializer=api__pb2.InfoRequest.FromString,
            response_serializer=api__pb2.PluginInfo.SerializeToString,
        ),
        "NotifyRegistrationStatus": grpc.unary_unary_rpc_method_handler(
            servicer.NotifyRegistrationStatus,
            request_deserializer=api__pb2.RegistrationStatus.FromString,
            response_serializer=api__pb2.RegistrationStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("pluginregistration.Registration", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("pluginregistration.Registration", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Registration(object):
    """Registration is the service advertised by the Plugins."""

    @staticmethod
    def GetInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pluginregistration.Registration/GetInfo",
            api__pb2.InfoRequest.SerializeToString,
            api__pb2.PluginInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def NotifyRegistrationStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/pluginregistration.Registration/NotifyRegistrationStatus",
            api__pb2.RegistrationStatus.SerializeToString,
            api__pb2.RegistrationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
