# -*- coding: utf-8 -*-
# ruff: noqa: E501
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "api.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tapi.proto\x12\x12pluginregistration"V\n\nPluginInfo\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12\x1a\n\x12supported_versions\x18\x04 \x03(\t">\n\x12RegistrationStatus\x12\x19\n\x11plugin_registered\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t"\x1c\n\x1aRegistrationStatusResponse"\r\n\x0bInfoRequest2\xd2\x01\n\x0cRegistration\x12L\n\x07GetInfo\x12\x1f.pluginregistration.InfoRequest\x1a\x1e.pluginregistration.PluginInfo"\x00\x12t\n\x18NotifyRegistrationStatus\x12&.pluginregistration.RegistrationStatus\x1a..pluginregistration.RegistrationStatusResponse"\x00\x42/Z-k8s.io/kubelet/pkg/apis/pluginregistration/v1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "api_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z-k8s.io/kubelet/pkg/apis/pluginregistration/v1"
    _globals["_PLUGININFO"]._serialized_start = 33
    _globals["_PLUGININFO"]._serialized_end = 119
    _globals["_REGISTRATIONSTATUS"]._serialized_start = 121
    _globals["_REGISTRATIONSTATUS"]._serialized_end = 183
    _globals["_REGISTRATIONSTATUSRESPONSE"]._serialized_start = 185
    _globals["_REGISTRATIONSTATUSRESPONSE"]._serialized_end = 213
    _globals["_INFOREQUEST"]._serialized_start = 215
    _globals["_INFOREQUEST"]._serialized_end = 228
    _globals["_REGISTRATION"]._serialized_start = 231
    _globals["_REGISTRATION"]._serialized_end = 441
# @@protoc_insertion_point(module_scope)
