apiVersion: v1
kind: Pod
metadata:
  name: reg-stub
  namespace: spire-system
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  hostNetwork: false
  hostIPC: false
  hostPID: false
  containers:
  - name: reg-stub
    image: python:3.11-slim
    command: ["/bin/sh","-c","sleep 1d"]
    volumeMounts:
    - name: plugins
      mountPath: /host/plugins_registry
  restartPolicy: Never
  volumes:
  - name: plugins
    hostPath:
      path: /var/lib/kubelet/plugins_registry
      type: DirectoryOrCreate
