apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tempo-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: tf-observability
spec:
  selector:
    matchLabels:
      app: tempo
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http-api
      interval: 15s
      path: /metrics
