# platform/deploy/infra/otel/templates/otel-identity.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-gateway
  namespace: observability
  labels:
    app: otel-gateway

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-agent
  namespace: observability
  labels:
    app: otel-agent

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: observability-mtls
  namespace: observability
spec:
  mtls:
    mode: STRICT
