apiVersion: v1
kind: ConfigMap
metadata:
  name: workers-config
data:
  REDIS_HOST: {{ .Values.env.REDIS_HOST }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
  POSTGRES_HOST: {{ .Values.env.POSTGRES_HOST }}
  POSTGRES_PORT: {{ .Values.env.POSTGRES_PORT | quote }}
  OLLAMA_API_BASE: {{ .Values.env.OLLAMA_API_BASE }}
