apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workers-rolebinding
subjects:
  - kind: ServiceAccount
    name: workers-sa
roleRef:
  kind: Role
  name: workers-role
  apiGroup: rbac.authorization.k8s.io
