apiVersion: 1

datasources:
  - name: ClickHouse-Value-Plane
    type: vertamedia-clickhouse-datasource
    access: proxy
    isDefault: false
    editable: false
    jsonData:
      host: clickhouse.threadforge-system.svc.cluster.local
      port: 9000
      database: value_plane
      protocol: native
      username: default
      tlsSkipVerify: true
      defaultTable: cost_model
    secureJsonData: {}