apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: Namespace
metadata:
  name: router
---
apiVersion: v1
kind: Namespace
metadata:
  name: workers
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: tempo
  labels:
    istio-injection: enabled
    threadforge.io/mesh: allowed
    pod-security.kubernetes.io/enforce: restricted
    threadforge-tier: observability