{{- $secretName := .Values.existingSecretName | default "minio-secrets" -}}
{{- if and .Values.rootUser .Values.rootPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | default "minio" }}
type: Opaque
stringData:
  accesskey: {{ .Values.rootUser | quote }}
  secretkey: {{ .Values.rootPassword | quote }}
{{- end }}
