#!/usr/bin/env bash
# requires_identity=true  # trust_tier=partial

if ! bash platform/runtime/operator/identity_enforcer.sh --require-partial >/dev/null 2>&1; then
  echo "ERROR: execution denied — identity enforcement requires partial or full trust tier. Read-only mode enforced." >&2
  echo "[ADVISORY-FAIL] non-authoritative path"; exit 2
fi
# tools/dev/demo/generate_full_demo_sql.sh
# Generate deterministic demo SQL mapping each observed pod|namespace to an identity mapping.
# The generated file defaults to a temporary/demo-local path supplied by the caller.

set -euo pipefail

OUT_FILE="${DEMO_FULL_SQL_OUTPUT:-tools/dev/demo/demo_identity_authority_full.sql}"
TMP_FILE="/tmp/demo_pods_namespaces.txt"

# Capture canonical evidence set (exact DISTINCT pod, namespace from memory_usage_snapshots)
kubectl -n threadforge-system exec -i sts/clickhouse -- clickhouse-client -q "SELECT distinct pod, namespace FROM value_plane.memory_usage_snapshots ORDER BY namespace, pod" --format=TSV > "$TMP_FILE"

# Start SQL file with a canonical_evidence CTE (read-only snapshot) for reviewer auditability
cat > "$OUT_FILE" <<'SQL'
-- demo_identity_authority_full.sql
-- Deterministic demo identity authority full mapping for CIV demo mode
-- DO NOT EDIT: generated by tools/dev/demo/generate_full_demo_sql.sh
--
-- canonical_evidence CTE (read-only snapshot of value_plane.memory_usage_snapshots used by the Civ test)
-- This CTE guarantees the full-authority mapping targets the exact evidence set used by the enrichment run.

SQL

# Build canonical_evidence as an inline SELECT UNION ALL (safe, read-only)
first_row=true
echo "-- canonical_evidence (read-only snapshot)" >> "$OUT_FILE"
echo -n "SELECT 'placeholder' AS pod, 'placeholder' AS namespace" > /tmp/ctesql.$$ || true
# Replace placeholder with the first real row below
rm -f /tmp/ctesql.$$

cteselect=""
while IFS=$'\t' read -r pod ns; do
  if [ -z "$pod" ] || [ -z "$ns" ]; then
    continue
  fi
  # escape single quotes
  pod_esc=$(printf "%s" "$pod" | sed "s/'/''/g")
  ns_esc=$(printf "%s" "$ns" | sed "s/'/''/g")
  if [ -z "$cteselect" ]; then
    cteselect="SELECT '${pod_esc}' AS pod, '${ns_esc}' AS namespace"
  else
    cteselect="${cteselect}"$'\n'"UNION ALL SELECT '${pod_esc}', '${ns_esc}'"
  fi
done < "$TMP_FILE"

if [ -z "$cteselect" ]; then
  echo "-- No canonical evidence rows found; generated SQL will be a no-op." >> "$OUT_FILE"
else
  echo "$cteselect;" >> "$OUT_FILE"
fi

# Now append deterministic, per-evidence-row INSERT statements derived from the same set
# Each INSERT is deterministic: id derived from md5(pod/namespace), fixed timestamps, and payload includes authority_source
while IFS=$'\t' read -r pod ns; do
  if [ -z "$pod" ] || [ -z "$ns" ]; then
    continue
  fi
  pod_esc_json=$(printf "%s" "$pod" | sed 's/"/\\"/g')
  ns_esc_json=$(printf "%s" "$ns" | sed 's/"/\\"/g')
  # compute deterministic md5 and format as UUID-like strings
  md5hex=$(printf "%s/%s" "$pod" "$ns" | md5 | awk '{print $NF}')
  src_evt_id=$(echo "$md5hex" | sed -E 's/^(.{8})(.{4})(.{4})(.{4})(.{12})/\1-\2-\3-\4-\5/')
  evt_id=$(echo "$md5hex" | sed -E 's/^(.{8})(.{4})(.{4})(.{4})(.{12})/aaaa\2-bbbb-cccc-dddd-eeeeeeeeeeee/')
  identity_class="demo-full/${ns}/${pod}"
  payload='{"pod":"'"$pod_esc_json"'","namespace":"'"$ns_esc_json"'","authority_source":"demo-authority-full"}'
  # Use source_ledger = 'demo-authority-full' per requirement
  printf "INSERT INTO value_plane.operator_ledger_v2 (source_event_id, source_ledger, ingest_run_id, ingested_at, event_id, created_at, spiffe_id, identity_class, payload) VALUES ('%s', 'demo-authority-full', 'ffffffff-ffff-ffff-ffff-ffffffffffff', toDateTime('2026-01-08 00:00:00'), '%s', toDateTime('2026-01-08 00:00:00'), '', '%s', '%s');\n" "$src_evt_id" "$evt_id" "$identity_class" "$payload" >> "$OUT_FILE"
done < "$TMP_FILE"

# Cleanup
rm -f "$TMP_FILE"

echo "Generated $OUT_FILE"
