{{- if .Values.spireServer.sql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.spireServer.sql.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.spireServer.sql.connectionKey }}: "postgresql://threadforge_operator:threadforge@postgres.threadforge-system.svc:5432/spire?sslmode=disable"
{{- end }}
