# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: threadforge_execution.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

# ruff: noqa: E501
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "threadforge_execution.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1bthreadforge_execution.proto\x12\x18threadforge.execution.v1"\x8c\x01\n\x0e\x45xecuteRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x16\n\x0e\x61\x63tor_identity\x18\x02 \x01(\t\x12\x16\n\x0eidentity_class\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x10\n\x08resource\x18\x05 \x01(\t\x12\x14\n\x0cpayload_json\x18\x06 \x01(\x0c"K\n\x0f\x45xecuteResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07outcome\x18\x02 \x01(\t\x12\x13\n\x0bresult_json\x18\x03 \x01(\x0c\x32r\n\x10\x45xecutionService\x12^\n\x07\x45xecute\x12(.threadforge.execution.v1.ExecuteRequest\x1a).threadforge.execution.v1.ExecuteResponseB&P\x01Z"threadforge/execution/v1;executionb\x06proto3',
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "threadforge_execution_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b'P\001Z"threadforge/execution/v1;execution'
    _globals["_EXECUTEREQUEST"]._serialized_start = 58
    _globals["_EXECUTEREQUEST"]._serialized_end = 198
    _globals["_EXECUTERESPONSE"]._serialized_start = 200
    _globals["_EXECUTERESPONSE"]._serialized_end = 275
    _globals["_EXECUTIONSERVICE"]._serialized_start = 277
    _globals["_EXECUTIONSERVICE"]._serialized_end = 391
# @@protoc_insertion_point(module_scope)
