apiVersion: batch/v1
kind: Job
metadata:
  name: spire-register-minio-envoy
  namespace: spire-system
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: spire-server
      containers:
      - name: spire-cli
        image: registry.threadforge.local:30500/spiffe/spire-server@sha256:817a87c37a6b77ff74c95908160ee0555daac8d8269e2fd7ad2b6e41b86164d8
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
        args:
        - -config
        - /run/spire/config/server.conf
        - entry
        - create
        - -spiffeID
        - spiffe://identity.threadforge.local/ns/minio/sa/minio-envoy
        - -selector
        - k8s:ns:minio
        - -selector
        - k8s:sa:minio-envoy
        - -ttl
        - "3600"
        volumeMounts:
        - name: spire-config
          mountPath: /run/spire/config
      volumes:
      - name: spire-config
        configMap:
          name: spire-server
  backoffLimit: 1
